---
- name: Apache deployment - 1st play
  hosts: all
  force_handlers: yes
  vars_files:
     - var.yml 
  tasks:
    - name: Install required packages.
      yum:
        name: "{{ list_of_package }}" 
        state: present
      when: ansible_fqdn in groups['prod']

    - name: Start and enable required services.
      service:
         name: "{{ item }}"
         state: started 
         enabled: yes
      loop: "{{ list_of_service }}"
      when: ansible_fqdn in groups['prod']
  
    - name: Check -  directory
      stat: 
        path: /var/www/html/vhost/
      register: output_apache
      when: ansible_fqdn in groups['prod']


    - name: Create directory
      file: 
        path: /var/www/html/vhost
        owner: apache
        group: apache
        state: directory
      #when: output_apache.stat.exists == false and ansible_fqdn in groups['prod']
      when: 
         - output_apache.stat.exists == false 
         - ansible_fqdn in groups['prod']

    - name: Configuration change - /var/www/html/vhost/
      copy:
         src: apache.conf
         dest: /etc/httpd/conf.d/apache.conf
      when: ansible_fqdn in groups['prod']
      notify:
        - apache_restart


    - name: Deploy application
      copy: 
         content: "This is my web server - {{ ansible_hostname }} \n"
         dest: /var/www/html/vhost/index.html
      when: ansible_fqdn in groups['prod']
  handlers: 
      - name: apache_restart
        service:
          name: httpd
          state: restarted
      when: ansible_fqdn in groups['prod']

- name: Verify the deployment.
  hosts: myself 
  vars_files:
     - var.yml
  become: false 
  tasks:
    - name: Check deployment
      uri: 
         url: http://{{item}}
         return_content: yes
         status_code: 200
      loop: "{{ server_list }}"
