---
- name: Apache deployment - 1st play
  hosts: prod
  force_handlers: yes
  vars_files:
     - var.yml 
  tasks:
    - name: Install required packages.
      yum:
        name: "{{ list_of_package }}" 
        state: present

    - name: Start and enable required services.
      service:
         name: "{{ item }}"
         state: started 
         enabled: yes
      loop: "{{ list_of_service }}"
  
    - name: Check -  directory
      stat: 
        path: /var/www/html/vhost/
      register: output_apache


    - name: Create directory
      file: 
        path: /var/www/html/vhost
        owner: apache
        group: apache
        state: directory
      when: output_apache.stat.exists == false

    - name: Configuration change - /var/www/html/vhost/
      copy:
         src: apache.conf
         dest: /etc/httpd/conf.d/apache.conf
      notify:
        - apache_restart


    - name: Deploy application
      copy: 
         content: "This is my web server - {{ ansible_hostname }} \n"
         dest: /var/www/html/vhost/index.html
  handlers: 
      - name: apache_restart
        service:
          name: httpd
          state: restarted

- name: Verify the deployment.
  hosts: myself 
  vars_files:
     - var.yml
  become: false 
  tasks:
    - name: Check deployment
      uri: 
         url: http://{{item}}
         return_content: yes
         status_code: 200
      loop: "{{ server_list }}"
