---
- name: Import example
  hosts: prod 
  tasks:
    - name: task-01 
      debug: 
        msg: "This is task-01"

    - name: include task 
      include_tasks: includeee_task.yaml

    - name: task-03
      debug: 
        msg: "This is task-03"
...
