---
- name: Reset root password.
  hosts: prod,dev
  vars_files:
       - var_vault.yaml
  tasks:
    - name:
      user:
         name: user1
         #name: root
         state: present
         password: "{{ root_password | password_hash('sha512') }}"
...

