---
- name: Setup your on ansible facts.
  hosts: dev,prod
  vars:
    - remote_dir: /etc/ansible/facts.d
      facts_file: cprakash.fact 
  tasks:
    - name: Create the remote dir
      file:
        path: "{{ remote_dir }}"
        state: directory 
        recurse: yes
    - name: INstalling facts.
      copy:
        src: "{{ facts_file }}"
        dest: "{{ remote_dir }}"
...
        
