---
- name: Query example 
  hosts: myself 
  tasks:
     - name: Display output 
       debug: 
         #msg: "{{ item[0] }}"
         msg: "{{ item[1] }}"
       loop: 
         #- "{{ query('lines', 'cat /tmp/hosts01') }}"
         #- "{{ query('lines', 'cat /tmp/hosts02') }}"
         - "{{ query('lines', 'cat hosts01') }}"
         - "{{ query('lines', 'cat hosts02') }}"
