---
- name: User creation and setup randam passwd       
  hosts: prod 
  gather_facts: no
  vars_files:
      - user_list.yaml 
  tasks:
      - name: User addition.
        vars:
          my_passwd: "{{ lookup('password','password-' + item.name + ' length=6 chars=digits') }}"
        user:
           name: "{{ item.name}}"
           state: present
           password: "{{ my_passwd | password_hash('sha512')}}"
           comment: "{{ item.first | capitalize }} {{ item.middle  | capitalize }} {{ item.last | capitalize}}"
           update_password: on_create
        loop: "{{ users_list }}"
